"""Schema inicial consolidado.

Revision ID: 20260813_0001_baseline
Revises:
Create Date: 2026-08-14 02:32:03.635332
"""
import sqlalchemy as sa
from alembic import op


revision = '20260813_0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('acronym', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brokers')),
    sa.UniqueConstraint('acronym', name=op.f('uq_brokers_acronym')),
    sa.UniqueConstraint('name', name=op.f('uq_brokers_name'))
    )
    op.create_table('option_expirations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_code', sa.String(length=5), nullable=False),
    sa.Column('put_code', sa.String(length=5), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_expirations')),
    sa.UniqueConstraint('call_code', name=op.f('uq_option_expirations_call_code')),
    sa.UniqueConstraint('exercise_date', name=op.f('uq_option_expirations_exercise_date')),
    sa.UniqueConstraint('put_code', name=op.f('uq_option_expirations_put_code'))
    )
    op.bulk_insert(
        sa.table(
            'option_expirations',
            sa.column('call_code', sa.String),
            sa.column('put_code', sa.String),
            sa.column('exercise_date', sa.Date),
        ),
        [
            {'call_code': f'{year}{call}', 'put_code': f'{year}{put}', 'exercise_date': date}
            for year, call, put, date in [
                (2024, 'F', 'R', '2024-06-21'), (2024, 'G', 'S', '2024-07-19'),
                (2024, 'H', 'T', '2024-08-16'), (2024, 'I', 'U', '2024-09-20'),
                (2024, 'J', 'V', '2024-10-18'), (2024, 'K', 'W', '2024-11-14'),
                (2024, 'L', 'X', '2024-12-20'), (2025, 'A', 'M', '2025-01-17'),
                (2025, 'B', 'N', '2025-02-21'), (2025, 'C', 'O', '2025-03-21'),
                (2025, 'D', 'P', '2025-04-18'), (2025, 'E', 'Q', '2025-05-16'),
                (2025, 'F', 'R', '2025-06-20'), (2025, 'G', 'S', '2025-07-18'),
                (2025, 'H', 'T', '2025-08-22'), (2025, 'I', 'U', '2025-09-19'),
                (2025, 'J', 'V', '2025-10-17'), (2025, 'K', 'W', '2025-11-21'),
                (2025, 'L', 'X', '2025-12-19'), (2026, 'A', 'M', '2026-01-16'),
                (2026, 'B', 'N', '2026-02-20'), (2026, 'C', 'O', '2026-03-20'),
                (2026, 'D', 'P', '2026-04-17'), (2026, 'E', 'Q', '2026-05-15'),
            ]
        ],
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IS NULL OR currency IN ('BRL', 'USD')", name=op.f('ck_portfolios_currency_valid')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_portfolios_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('name', name=op.f('uq_portfolios_name'))
    )
    op.bulk_insert(
        sa.table(
            'portfolios',
            sa.column('name', sa.String),
            sa.column('currency', sa.String),
            sa.column('simulated', sa.Boolean),
        ),
        [
            {'name': 'BRL', 'currency': 'BRL', 'simulated': False},
            {'name': 'USD', 'currency': 'USD', 'simulated': False},
            {'name': 'Simulada', 'currency': None, 'simulated': True},
        ],
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('trading_name', sa.String(length=80), nullable=False),
    sa.Column('market', sa.Enum('B3', 'NYSE', 'NASDAQ', name='market'), nullable=False),
    sa.Column('rtd_market_code', sa.String(length=1), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('BRL', 'USD')", name=op.f('ck_tickers_currency_valid')),
    sa.CheckConstraint("rtd_market_code IN ('B', 'Y', 'N')", name=op.f('ck_tickers_rtd_market_code_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickers')),
    sa.UniqueConstraint('symbol', name=op.f('uq_tickers_symbol'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_mode', sa.Enum('EXCEL', 'DIRECT', name='collector_mode'), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('risk_free_rate_annual', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('benchmark_ticker_id', sa.Integer(), nullable=True),
    sa.Column('stale_alert_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_free_rate_annual NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_app_settings_risk_free_rate_annual_finite')),
    sa.CheckConstraint('id = 1', name=op.f('ck_app_settings_singleton')),
    sa.CheckConstraint('poll_interval_seconds BETWEEN 1 AND 3600', name=op.f('ck_app_settings_poll_interval_seconds_range')),
    sa.CheckConstraint('risk_free_rate_annual BETWEEN 0 AND 1', name=op.f('ck_app_settings_risk_free_rate_annual_range')),
    sa.CheckConstraint('stale_alert_seconds IS NULL OR stale_alert_seconds BETWEEN 1 AND 86400', name=op.f('ck_app_settings_stale_alert_seconds_range')),
    sa.ForeignKeyConstraint(['benchmark_ticker_id'], ['tickers.id'], name=op.f('fk_app_settings_benchmark_ticker_id_tickers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.execute(
        sa.text(
            "INSERT INTO app_settings "
            "(id, collector_mode, poll_interval_seconds, risk_free_rate_annual) "
            "VALUES (1, 'EXCEL', 2, 0.1075)"
        )
    )
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_dividends_amount_finite')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_dividends_amount_positive')),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_dividends_broker_id_brokers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_dividends_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividends'))
    )
    op.create_index(op.f('ix_dividends_broker_id'), 'dividends', ['broker_id'], unique=False)
    op.create_index(op.f('ix_dividends_payment_date'), 'dividends', ['payment_date'], unique=False)
    op.create_index(op.f('ix_dividends_ticker_id'), 'dividends', ['ticker_id'], unique=False)
    op.create_table('option_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('underlying_ticker_id', sa.Integer(), nullable=False),
    sa.Column('expiration_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.Enum('CALL', 'PUT', name='option_type'), nullable=False),
    sa.Column('strike', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.CheckConstraint("strike NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_contracts_strike_finite')),
    sa.CheckConstraint('strike >= 0', name=op.f('ck_option_contracts_strike_non_negative')),
    sa.ForeignKeyConstraint(['expiration_id'], ['option_expirations.id'], name=op.f('fk_option_contracts_expiration_id_option_expirations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_option_contracts_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['underlying_ticker_id'], ['tickers.id'], name=op.f('fk_option_contracts_underlying_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_contracts')),
    sa.UniqueConstraint('ticker_id', name=op.f('uq_option_contracts_ticker_id'))
    )
    op.create_table('portfolio_tickers',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_tickers_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_portfolio_tickers_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('portfolio_id', 'ticker_id', name=op.f('pk_portfolio_tickers'))
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='position_side'), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('quote_multiplier', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('target_multiplier', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('result_mode', sa.String(length=1), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("average_cost NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_positions_average_cost_finite')),
    sa.CheckConstraint("quantity NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_positions_quantity_finite')),
    sa.CheckConstraint("quote_multiplier NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_positions_quote_multiplier_finite')),
    sa.CheckConstraint("result_mode IN ('L', 'B')", name=op.f('ck_positions_result_mode_valid')),
    sa.CheckConstraint("target_multiplier NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_positions_target_multiplier_finite')),
    sa.CheckConstraint('average_cost >= 0', name=op.f('ck_positions_average_cost_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_positions_quantity_positive')),
    sa.CheckConstraint('quote_multiplier > 0', name=op.f('ck_positions_quote_multiplier_positive')),
    sa.CheckConstraint('target_multiplier > 0', name=op.f('ck_positions_target_multiplier_positive')),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_positions_broker_id_brokers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_positions_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_broker_id'), 'positions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_ticker_id'), 'positions', ['ticker_id'], unique=False)
    op.create_table('quote_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_quote_history_price_finite')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_quote_history_price_non_negative')),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_quote_history_ticker_id_tickers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_history')),
    sa.UniqueConstraint('ticker_id', 'recorded_date', name='uq_quote_history_ticker_date')
    )
    op.create_index(op.f('ix_quote_history_recorded_date'), 'quote_history', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_quote_history_ticker_id'), 'quote_history', ['ticker_id'], unique=False)
    op.create_table('option_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='position_side'), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('result_mode', sa.String(length=1), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("average_cost NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_positions_average_cost_finite')),
    sa.CheckConstraint("quantity NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_positions_quantity_finite')),
    sa.CheckConstraint("result_mode IN ('L', 'B')", name=op.f('ck_option_positions_result_mode_valid')),
    sa.CheckConstraint("target_price IS NULL OR target_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_positions_target_finite')),
    sa.CheckConstraint('average_cost >= 0', name=op.f('ck_option_positions_average_cost_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_option_positions_quantity_positive')),
    sa.CheckConstraint('target_price IS NULL OR target_price >= 0', name=op.f('ck_option_positions_target_non_negative')),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_option_positions_broker_id_brokers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], name=op.f('fk_option_positions_contract_id_option_contracts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_option_positions_portfolio_id_portfolios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_positions'))
    )
    op.create_index(op.f('ix_option_positions_broker_id'), 'option_positions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_option_positions_contract_id'), 'option_positions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_option_positions_portfolio_id'), 'option_positions', ['portfolio_id'], unique=False)
    op.create_table('quotes',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('instrument_status', sa.String(length=16), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(length=250), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("last_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_quotes_last_price_finite')),
    sa.CheckConstraint("previous_close NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_quotes_previous_close_finite')),
    sa.CheckConstraint('last_price >= 0', name=op.f('ck_quotes_last_price_non_negative')),
    sa.CheckConstraint('previous_close >= 0', name=op.f('ck_quotes_previous_close_non_negative')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_quotes_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', name=op.f('pk_quotes'))
    )
    op.create_index(op.f('ix_quotes_observed_at'), 'quotes', ['observed_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('option_contract_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='position_side'), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('result_mode', sa.String(length=1), nullable=False),
    sa.Column('result', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='transaction_status'), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('source_position_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'OPEN' AND closed_on IS NULL AND exit_price IS NULL AND result IS NULL) OR (status = 'CLOSED' AND closed_on IS NOT NULL AND exit_price IS NOT NULL AND result IS NOT NULL)", name=op.f('ck_transactions_status_fields_consistency')),
    sa.CheckConstraint("average_cost NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_transactions_average_cost_finite')),
    sa.CheckConstraint("exit_price IS NULL OR exit_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_transactions_exit_price_finite')),
    sa.CheckConstraint("quantity NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_transactions_quantity_finite')),
    sa.CheckConstraint("result IS NULL OR result NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_transactions_result_finite')),
    sa.CheckConstraint("result_mode IN ('L', 'B')", name=op.f('ck_transactions_result_mode_valid')),
    sa.CheckConstraint('average_cost >= 0', name=op.f('ck_transactions_average_cost_non_negative')),
    sa.CheckConstraint('closed_on IS NULL OR closed_on >= opened_on', name=op.f('ck_transactions_closed_on_not_before_opened_on')),
    sa.CheckConstraint('exit_price IS NULL OR exit_price >= 0', name=op.f('ck_transactions_exit_price_non_negative')),
    sa.CheckConstraint('num_nonnulls(ticker_id, option_contract_id) = 1', name=op.f('ck_transactions_exactly_one_instrument')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_transactions_quantity_positive')),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_transactions_broker_id_brokers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], name=op.f('fk_transactions_option_contract_id_option_contracts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], name=op.f('fk_transactions_ticker_id_tickers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_broker_id'), 'transactions', ['broker_id'], unique=False)
    op.create_index(op.f('ix_transactions_closed_on'), 'transactions', ['closed_on'], unique=False)
    op.create_index(op.f('ix_transactions_option_contract_id'), 'transactions', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transactions_ticker_id'), 'transactions', ['ticker_id'], unique=False)
    op.create_index('uq_transactions_open_source_position_option', 'transactions', ['source_position_id'], unique=True, postgresql_where=sa.text("status = 'OPEN' AND option_contract_id IS NOT NULL"))
    op.create_index('uq_transactions_open_source_position_stock', 'transactions', ['source_position_id'], unique=True, postgresql_where=sa.text("status = 'OPEN' AND ticker_id IS NOT NULL"))
    op.create_table('option_position_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_position_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('OPEN', 'INCREASE', 'DECREASE', 'ADJUSTMENT', name='position_movement_kind'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('result', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('resulting_average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'DECREASE') = (result IS NOT NULL)", name=op.f('ck_option_position_movements_result_only_on_decrease')),
    sa.CheckConstraint("(kind IN ('OPEN', 'INCREASE') AND quantity_delta > 0) OR (kind = 'DECREASE' AND quantity_delta < 0) OR kind = 'ADJUSTMENT'", name=op.f('ck_option_position_movements_quantity_delta_sign_matches_kind')),
    sa.CheckConstraint("price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_position_movements_price_finite')),
    sa.CheckConstraint("quantity_delta NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_position_movements_quantity_delta_finite')),
    sa.CheckConstraint("result IS NULL OR result NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_position_movements_result_finite')),
    sa.CheckConstraint("resulting_average_cost NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_position_movements_resulting_average_cost_finite')),
    sa.CheckConstraint("resulting_quantity NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_position_movements_resulting_quantity_finite')),
    sa.CheckConstraint("transaction_id IS NULL OR kind = 'DECREASE'", name=op.f('ck_option_position_movements_transaction_only_on_decrease')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_option_position_movements_price_non_negative')),
    sa.CheckConstraint('resulting_average_cost >= 0', name=op.f('ck_option_position_movements_resulting_average_cost_non_negative')),
    sa.CheckConstraint('resulting_quantity > 0', name=op.f('ck_option_position_movements_resulting_quantity_positive')),
    sa.ForeignKeyConstraint(['option_position_id'], ['option_positions.id'], name=op.f('fk_option_position_movements_option_position_id_option_positions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_option_position_movements_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_position_movements')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_option_position_movements_transaction_id'))
    )
    op.create_index(op.f('ix_option_position_movements_option_position_id'), 'option_position_movements', ['option_position_id'], unique=False)
    op.create_table('option_quotes',
    sa.Column('option_position_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('underlying_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('instrument_status', sa.String(length=16), nullable=False),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(length=250), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("last_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_quotes_last_price_finite')),
    sa.CheckConstraint("previous_close NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_quotes_previous_close_finite')),
    sa.CheckConstraint("underlying_price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_option_quotes_underlying_price_finite')),
    sa.CheckConstraint('last_price >= 0', name=op.f('ck_option_quotes_last_price_non_negative')),
    sa.CheckConstraint('previous_close >= 0', name=op.f('ck_option_quotes_previous_close_non_negative')),
    sa.CheckConstraint('underlying_price >= 0', name=op.f('ck_option_quotes_underlying_price_non_negative')),
    sa.ForeignKeyConstraint(['option_position_id'], ['option_positions.id'], name=op.f('fk_option_quotes_option_position_id_option_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_position_id', name=op.f('pk_option_quotes'))
    )
    op.create_index(op.f('ix_option_quotes_observed_at'), 'option_quotes', ['observed_at'], unique=False)
    op.create_table('position_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('OPEN', 'INCREASE', 'DECREASE', 'ADJUSTMENT', name='position_movement_kind'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('result', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('resulting_average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'DECREASE') = (result IS NOT NULL)", name=op.f('ck_position_movements_result_only_on_decrease')),
    sa.CheckConstraint("(kind IN ('OPEN', 'INCREASE') AND quantity_delta > 0) OR (kind = 'DECREASE' AND quantity_delta < 0) OR kind = 'ADJUSTMENT'", name=op.f('ck_position_movements_quantity_delta_sign_matches_kind')),
    sa.CheckConstraint("price NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_position_movements_price_finite')),
    sa.CheckConstraint("quantity_delta NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_position_movements_quantity_delta_finite')),
    sa.CheckConstraint("result IS NULL OR result NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_position_movements_result_finite')),
    sa.CheckConstraint("resulting_average_cost NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_position_movements_resulting_average_cost_finite')),
    sa.CheckConstraint("resulting_quantity NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)", name=op.f('ck_position_movements_resulting_quantity_finite')),
    sa.CheckConstraint("transaction_id IS NULL OR kind = 'DECREASE'", name=op.f('ck_position_movements_transaction_only_on_decrease')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_position_movements_price_non_negative')),
    sa.CheckConstraint('resulting_average_cost >= 0', name=op.f('ck_position_movements_resulting_average_cost_non_negative')),
    sa.CheckConstraint('resulting_quantity > 0', name=op.f('ck_position_movements_resulting_quantity_positive')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_movements_position_id_positions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_position_movements_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_movements')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_position_movements_transaction_id'))
    )
    op.create_index(op.f('ix_position_movements_position_id'), 'position_movements', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_movements_position_id'), table_name='position_movements')
    op.drop_table('position_movements')
    op.drop_index(op.f('ix_option_quotes_observed_at'), table_name='option_quotes')
    op.drop_table('option_quotes')
    op.drop_index(op.f('ix_option_position_movements_option_position_id'), table_name='option_position_movements')
    op.drop_table('option_position_movements')
    op.drop_index('uq_transactions_open_source_position_stock', table_name='transactions', postgresql_where=sa.text("status = 'OPEN' AND ticker_id IS NOT NULL"))
    op.drop_index('uq_transactions_open_source_position_option', table_name='transactions', postgresql_where=sa.text("status = 'OPEN' AND option_contract_id IS NOT NULL"))
    op.drop_index(op.f('ix_transactions_ticker_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_option_contract_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_closed_on'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_broker_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_quotes_observed_at'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_option_positions_portfolio_id'), table_name='option_positions')
    op.drop_index(op.f('ix_option_positions_contract_id'), table_name='option_positions')
    op.drop_index(op.f('ix_option_positions_broker_id'), table_name='option_positions')
    op.drop_table('option_positions')
    op.drop_index(op.f('ix_quote_history_ticker_id'), table_name='quote_history')
    op.drop_index(op.f('ix_quote_history_recorded_date'), table_name='quote_history')
    op.drop_table('quote_history')
    op.drop_index(op.f('ix_positions_ticker_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_broker_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('portfolio_tickers')
    op.drop_table('option_contracts')
    op.drop_index(op.f('ix_dividends_ticker_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_payment_date'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_broker_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('app_settings')
    op.drop_table('users')
    op.drop_table('tickers')
    op.drop_table('portfolios')
    op.drop_table('option_expirations')
    op.drop_table('brokers')
    # ### end Alembic commands ###
